"use client";
import React, { useState } from "react";
import { 
  LayoutDashboard, 
  FileText, 
  Brain, 
  Settings, 
  LogOut, 
  StickyNote, 
  Network 
} from "lucide-react";

const Dashboard = () => {
  const [active, setActive] = useState("Overview");

  const menuItems = [
    { name: "Overview", icon: LayoutDashboard },
    { name: "Notes", icon: StickyNote },
    { name: "Memory Graph", icon: Network },
    { name: "AI Insights", icon: Brain },
    { name: "Goals & Tasks", icon: FileText },
    { name: "Settings", icon: Settings },
  ];

  return (
    <div className="min-h-screen flex bg-gray-50">
      {/* Sidebar */}
      <aside className="w-64 bg-white shadow-xl flex flex-col justify-between fixed h-screen">
        <div>
          <div className="flex items-center justify-center py-6 border-b border-gray-200">
            <h1 className="text-2xl font-bold text-pink-600">NeuraLife</h1>
          </div>
          <nav className="mt-6 space-y-2">
            {menuItems.map((item) => {
              const Icon = item.icon;
              const isActive = active === item.name;
              return (
                <button
                  key={item.name}
                  onClick={() => setActive(item.name)}
                  className={`w-full flex items-center px-6 py-3 text-left transition ${
                    isActive
                      ? "bg-pink-100 text-pink-600 font-semibold"
                      : "text-gray-600 hover:bg-pink-50"
                  }`}
                >
                  <Icon className="w-5 h-5 mr-3" />
                  {item.name}
                </button>
              );
            })}
          </nav>
        </div>

        <div className="border-t border-gray-200 p-6">
          <button className="flex items-center text-gray-600 hover:text-pink-600 transition">
            <LogOut className="w-5 h-5 mr-2" />
            Logout
          </button>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 ml-64 p-10">
        <h1 className="text-3xl font-bold text-gray-800 mb-6">
          {active}
        </h1>

        {active === "Overview" && (
          <div className="grid md:grid-cols-3 gap-6">
            <div className="bg-white p-6 rounded-2xl shadow-lg">
              <h2 className="text-xl font-semibold text-pink-600 mb-2">Total Notes</h2>
              <p className="text-gray-600 text-3xl font-bold">128</p>
            </div>
            <div className="bg-white p-6 rounded-2xl shadow-lg">
              <h2 className="text-xl font-semibold text-pink-600 mb-2">Goals Completed</h2>
              <p className="text-gray-600 text-3xl font-bold">42</p>
            </div>
            <div className="bg-white p-6 rounded-2xl shadow-lg">
              <h2 className="text-xl font-semibold text-pink-600 mb-2">AI Suggestions</h2>
              <p className="text-gray-600 text-3xl font-bold">17</p>
            </div>
          </div>
        )}

        {active === "Notes" && (
          <div className="bg-white p-8 rounded-2xl shadow-lg">
            <h2 className="text-2xl font-bold mb-4 text-pink-600">Your Notes</h2>
            <p className="text-gray-600">
              Markdown-based notes with tagging and graph view — organize your thoughts seamlessly.
            </p>
            <div className="mt-6 border-t border-gray-200 pt-4">
              <button className="bg-pink-600 hover:bg-pink-700 text-white px-5 py-2 rounded-lg font-semibold">
                + Create New Note
              </button>
            </div>
          </div>
        )}

        {active === "Memory Graph" && (
          <div className="bg-white p-8 rounded-2xl shadow-lg">
            <h2 className="text-2xl font-bold mb-4 text-pink-600">Memory Graph</h2>
            <p className="text-gray-600">
              Visualize your connected thoughts like Obsidian — your second brain, visualized.
            </p>
            <div className="h-64 mt-6 bg-gray-100 rounded-xl flex items-center justify-center text-gray-500">
              [Interactive Graph Placeholder]
            </div>
          </div>
        )}

        {active === "AI Insights" && (
          <div className="bg-white p-8 rounded-2xl shadow-lg">
            <h2 className="text-2xl font-bold mb-4 text-pink-600">AI Insights</h2>
            <p className="text-gray-600 mb-4">
              Personalized suggestions and summaries generated by NeuraLife AI.
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>“You’ve been writing about productivity — try setting weekly goals.”</li>
              <li>“Your focus peaks at 10 AM. Schedule deep work then.”</li>
              <li>“3 related ideas found in your notes about ‘Habits’.”</li>
            </ul>
          </div>
        )}

        {active === "Goals & Tasks" && (
          <div className="bg-white p-8 rounded-2xl shadow-lg">
            <h2 className="text-2xl font-bold mb-4 text-pink-600">Goals & Tasks</h2>
            <p className="text-gray-600 mb-4">Track your goals and progress efficiently.</p>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="border border-gray-200 p-4 rounded-xl flex justify-between items-center">
                <span className="text-gray-700">Build morning routine</span>
                <input type="checkbox" className="w-5 h-5 accent-pink-600" />
              </div>
              <div className="border border-gray-200 p-4 rounded-xl flex justify-between items-center">
                <span className="text-gray-700">Write daily journal</span>
                <input type="checkbox" className="w-5 h-5 accent-pink-600" />
              </div>
            </div>
          </div>
        )}

        {active === "Settings" && (
          <div className="bg-white p-8 rounded-2xl shadow-lg">
            <h2 className="text-2xl font-bold mb-4 text-pink-600">Settings</h2>
            <p className="text-gray-600 mb-4">
              Manage preferences, themes, and synchronization settings.
            </p>
            <div className="space-y-4">
              <div>
                <label className="font-medium text-gray-700">Theme</label>
                <select className="block w-full mt-2 border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-pink-500">
                  <option>Light</option>
                  <option>Dark</option>
                </select>
              </div>
              <div>
                <label className="font-medium text-gray-700">Sync via</label>
                <select className="block w-full mt-2 border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-pink-500">
                  <option>Firebase</option>
                  <option>WebSockets</option>
                </select>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default Dashboard;
